services:
  frontend:
    build: 
      context: ./flightsearchfront
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./flightsearchback
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - SPRING_PROFILES_ACTIVE=dev
