version: '3.9'
services:
  backend:
    build:
      context: ./flightsearchback
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  frontend:
    build: 
      context: ./flightsearchfront
      dockerfile: Dockerfile
    ports:
      - "8080:8080"